### ISSUE TITLE
Why is everything doubling? Please fix

### ISSUE THREAD

**Issue by tfafard** [chippydip/HearthLog#8]
This is very very wrong, I have only played 4 games.
Why is everything doubling? Please fix

http://i.imgur.com/N9e4qDw.jpg

**Comment by tfafard** [comment]
Here again- I just won only 1 mage match and...  http://i.imgur.com/QozHZQX.jpg

**Comment by chippydip** [comment]
It looks like you might have more than one copy of the Hearth Log program running at the same time.

You'll notice that the game history is correctly displaying each game only once while the stats are counting results multiple times. I will be recalculating all stats on the site from the raw logs at some point in the not-too-distant future and adding a check to prevent this from happening in the future.

Making sure the logger can only run one copy at a time is also on the TODO list.

Until then, I'm sorry for the incorrect results, but there's not an easy way for me to manually fit it. Just make sure you are only running the logger once and your stats from here on out should be accurate.

**Comment by tfafard** [comment]
So do I un-install it? If so how do I locate all the files and delete them to re-install?

**Comment by chippydip** [comment]
There isn't currently an installer or un-installer for the actual logging program.

If you look in your system tray you should see multiple Hearthstone icons that say "Hearth Log" when you mouse over them. You can right-click and select "Exit" on all but one of them to fix the problem (might have to click the little "show hidden icons" arrow to see them all).

Alternately, you can open the Task Manager (right-click your taskbar and select "Start Task Manager"). In the "Processes" tab, click the "Image Name" column to sort by name and then find the "Hearth Log.exe *32" entries in the list. Right-click all but one entry and select "End Process" and then confirm your action in the pop-up.

You could also just restart your computer since Hearth Log doesn't currently run at startup (you have to manually launch it).

If you close all copies or restart your computer you will need to start the program again to re-enable logging. Just double-click the program from wherever you unzipped the download.

If you still have issues let me know and I'll see what I can do.

**Comment by tfafard** [comment]
It works thanks for everything, and ty for this, it helps my streamers know
how how good I am doing.

On Mon, Dec 9, 2013 at 5:58 PM, chippydip notifications@github.com wrote:

> There isn't currently an installer or un-installer for the actual logging
> program.
> 
> If you look in your system tray you should see multiple Hearthstone icons
> that say "Hearth Log" when you mouse over them. You can right-click and
> select "Exit" on all but one of them to fix the problem (might have to
> click the little "show hidden icons" arrow to see them all).
> 
> Alternately, you can open the Task Manager (right-click your taskbar and
> select "Start Task Manager"). In the "Processes" tab, click the "Image
> Name" column to sort by name and then find the "Hearth Log.exe *32" entries
> in the list. Right-click all but one entry and select "End Process" and
> then confirm your action in the pop-up.
> 
> You could also just restart your computer since Hearth Log doesn't
> currently run at startup (you have to manually launch it).
> 
> If you close all copies or restart your computer you will need to start
> the program again to re-enable logging. Just double-click the program from
> wherever you unzipped the download.
> 
> If you still have issues let me know and I'll see what I can do.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/chippydip/HearthLog/issues/8#issuecomment-30193126
> .

## 

-Tennesee "Church" Fafard

**Comment by jspri** [comment]
I've checked that I've only got one copy of hearthlog running yet am getting occasional doubles. Note the identical timestamps on SOME games. Similar to the other user the counter increments by a seemingly random amount. I', running windows 8.1 if that helps

http://imgur.com/5TCBe1C

Nice program by the way!

**Comment by chippydip** [comment]
@Crazometer 

Thank you for reporting this issue! It appears to be something completely different from this issue, so I've created a [new one](https://github.com/chippydip/HearthLog/issues/10) to track it.

The original issue of uploading the _same_ log twice should now be fixed, so I'm going to close this issue and work on this new problem in the new thread.
